#!/bin/bash
#SBATCH --job-name=runhisat2      # Job name
#SBATCH --partition=batch              # Partition (queue) name, i.e., highmem_p
#SBATCH --ntasks=1                          # Run a single task
#SBATCH --cpus-per-task=28                  # Number of CPU cores per task
#SBATCH --mem=180gb                          # Job memory request
#SBATCH --time=72:00:00                     # Time limit hrs:min:sec
#SBATCH --output=runhisat2.%j.out         # Standard output log
#SBATCH --error=runhisat2.%j.err          # Standard error log
#SBATCH --mail-type=END,FAIL                # Mail events (NONE, BEGIN, END, FAIL, ALLd)
#SBATCH --mail-user=taylor.strayhorn@uga.edu   # Where to send mail
#SBATCH --export=NONE                       # do not load any env variables to compute node


module load HISAT2/2.2.1-foss-2019b

mkdir "Mapped_Data/hisat2_out"

for file in "Mapped_Data/demultiplexed/"*s.fastq*
do
	file2="${file:26:-9}"

if [ ! -f "Mapped_Data/hisat2_out/""$file2"".bam" ]; then

	fastp -w 4 -i "$file" -o "Mapped_Data/hisat2_out/""$file2"".fastq.gz" -y -x -3 -a AAAAAAAAAAAA
	
	hisat2 -p 4 --dta -x Genome/Zm5UNos_noSS -U "Mapped_Data/hisat2_out/""$file2"".fastq.gz" | samtools view -bS -> "Mapped_Data/hisat2_out/""$file2""_unsorted.bam"
	
	samtools sort -@ 8 "Mapped_Data/hisat2_out/""$file2""_unsorted.bam" -o "Mapped_Data/hisat2_out/""$file2"".bam"
	
	find "Mapped_Data/hisat2_out/" -name "*fastq.gz" -delete
	find "Mapped_Data/hisat2_out/" -name "*_unsorted.bam" -delete
fi
done



for file in *.fastq.gz
do
  hisat2 -U "$file" | samtools view -bS > "${file:0:-9}"".bam"
done

for file in *.fastq.gz
do
  file2 = "${file:0:-9}"".bam"
done

echo "$file2"
