#!/bin/bash
#SBATCH --job-name=sortbam      # Job name
#SBATCH --partition=batch              # Partition (queue) name, i.e., highmem_p
#SBATCH --ntasks=1                          # Run a single task
#SBATCH --cpus-per-task=28                  # Number of CPU cores per task
#SBATCH --mem=30gb                          # Job memory request
#SBATCH --time=72:00:00                     # Time limit hrs:min:sec
#SBATCH --output=sortbam.%j.out         # Standard output log
#SBATCH --error=sortbam.%j.err          # Standard error log
#SBATCH --mail-type=END,FAIL                # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=taylor.strayhorn@uga.edu   # Where to send mail
#SBATCH --export=NONE                       # do not load any env variables to compute node

module load SAMtools/1.16.1-GCC-11.3.0

samtools sort -@ 8 -o *.sort.bam 
samotools index *.sort.bam 

for file in *.sort.bam 
echo "${file:(52+i)-4}" >> readcounts.txt 
