#!/bin/bash
#SBATCH --job-name=stringtie1       # Job name
#SBATCH --partition=batch              # Partition (queue) name, i.e., highmem_p
#SBATCH --ntasks=1                          # Run a single task
#SBATCH --cpus-per-task=28                  # Number of CPU cores per task
#SBATCH --mem=30gb                          # Job memory request
#SBATCH --time=72:00:00                     # Time limit hrs:min:sec
#SBATCH --output=stringtie.%j.out         # Standard output log
#SBATCH --error=stringtie.%j.err          # Standard error log
#SBATCH --mail-type=END,FAIL                # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=taylor.strayhorn@uga.edu   # Where to send mail
#SBATCH --export=NONE                       # do not load any env variables to compute node

module load StringTie/2.1.7-GCC-8.3.0

mkdir scratch/tms51355/TFproject/Salvo/stringtie_out 

for file in "scratch/tms51355/TFproject/Salvo"*.bam
do 
stringtie -p -4 -G Zm-B73-REFERENCE-NAM-5.0_Zm00001eb.1.gff3 --rf -o scratch/tms51355/TFproject/Salvo/stringtie_out/""$file:(32+i):-4"".gtf
"$file" 
done 
